# Generated by Django 3.2.3 on 2021-05-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('account_name', models.CharField(max_length=200, null=True)),
                ('payment_name', models.CharField(max_length=200, null=True)),
                ('number_of_boxes', models.IntegerField(default=1, null=True)),
                ('server', models.CharField(max_length=200, null=True)),
                ('mac_address', models.CharField(max_length=200, null=True)),
                ('expires', models.DateTimeField(null=True)),
                ('communication', models.CharField(max_length=200, null=True)),
                ('referal', models.CharField(max_length=200, null=True)),
                ('building_type', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('customer_since', models.DateField(null=True)),
                ('notes', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
