# Generated by Django 3.2.3 on 2021-05-26 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customer_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='needs_remind',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
